# !/usr/bin/ruby

da_quotes = [
  'Have you ever licked a lamp post in winter? ―Alistair',
  'My Fruit..... Well it\'s not technically forbidden but, but it\'d not freely given either ―Leliana',
  'Now, let us crush something soft and watch it fountain blood. That is a girlish thing to want to do, yes? ―Shale',
  'Yes, that\'s right! Watch as I thrash our enemies with the mighty power of floral arrangements! Feel my thorns, darkspawn! I will overpower you with my rosy scent! ―Alistair',
  'Oh no, big templar man! What are you going to do with that sword? ―Oghren',
  'You can probe me anytime. ―Warden',
  'Why would such a small people make things so tall? They must own an impressive array of ladders. -Sten',
  'A fine tactic. Provided it actually kills them and you don\'t end up having to deal with flaming undead. -Zevran',
  'Hey, look at me - I\'m an elf! Trees are pretty! Tra-la-la!  -Oghren',
  'Oh, I know, I know. Most people enjoy being kicked in the head to be woken up each morning. Me, I\'m just so picky.-Anders',
  'Men’s hearts hold shadows darker than any tainted creature. -Flemeth',
  'Andraste\'s flaming sword! I know where babies come from!-Allistair',
  'Of course the mages would choose to imprison themselves in a structure shaped like a giant phallus. ―Morrigan',
  'I’m here to set things right. Also? To look dashing. That part’s less difficult. -Dorian',
  'Aveline, my bulbous cherub, you must hear the droning of Lord Full-of-Shit. -Hawke',
  'Let those who would destroy us step into the light. —The Inquisitor',
  'Tell me, where is your Maker now? Call him. Call his wrath down upon me. You cannot. For he does not exist. —Corypheus',
  'It\'s dangerous when too many men in the same armor think they\'re right. —Cole',
  'Beg that I succeed, for I have seen the throne of the gods, and it was empty. —Corypheus',
  'What do you want from me? I broke in, found my brother and it was awkward. Y\'know, family business. -Varric',
  'We stand upon the precipice of change. The world fears the inevitable plummet into the abyss. Watch for that moment - and when it comes, do not hesitate to leap. It is only when you fall that you learn whether you can fly. -Flemeth',
  'I have six toes on my left foot. -Tallis',
  'Can\'t we talk about this? No? -Hawke',
  'If we kill them, we get their stuff! -Isabela',
  'Your death toll is approaching natural disasters! -Isabela',
  'We now have a dog and Alistair is still the dumbest one in the party. -―Morrigan',
  'Let\'s show them our hearts, and then show them theirs. -Oghren',
  'May the dirt taste good when I feed it to you. -Warden',
  'When in doubt, run away, and let me handle it. -Hawke',
  'What earth-shattering matter requires my attention this time? -Hawke',
  'We do a lot of walking, don\'t we? -Hawke',
  'And we\'re under attack. What a surprise! -Hawke',
  'Maker take you! -Inquisitor',
  'One day, they may write about me as a traitor, a madwoman, a fool. And they may be right. -Cassandra',
  'They will stand in the fire and complain that it is hot. -Cassandra',
  'Brace yourselves! Here comes the storm! -Isabela',
  'Nothing like a near-death experience to get the blood pumping. -Isabela',
  'Buck up, big girl. It\'s a wonderful day. -Isabela',
  'I\'m uncomfortable around Chantry sisters. All because of that redhaired trickster in Lothering. -Aveline',
  'How about I shove a canary up your coal mine? -Aveline',
  'Apostate prostitutes? Apostitutes! Hahaha! -Isabela',
  'Please speak up! I cannot hear you over your outfit! -Solas',
  'I like big boats, I cannot lie. -Isabela',
  'No. -Sten',
  'What do you suppose would happen if I tickled one of them? -Merrill',
  'Pretend you don\'t know this about me. -Cassandra',
  'I hear the Arishok was replaced by the Arishok. But he\'d better watch out. In the shadows, the Arishok. -Cabot',
  'Our mistakes make us who we are. -Isabela',
  'And then Isabela went to the chantry, and saw that it was boring. Canticle of Isabela, stanza one, verse one. -Isabela',
  'You see, sweetness, men are only good for one thing. Women are good for six. -Isabela',
  'Could you please not talk, I have the worst hangover. -Isabela',
  'Where\'s my lady battering ram when I need her. -Isabela',
  'Once more I am falsely accused of whatever it is that I am accused of. Falsely. -Varric',
  'I swear I am going to find that son of a bitch - sorry, Mother - and I will kill him! -Varric',
  'Baiting a dragon. On purpose. Right. Should have stayed home today. -Varric',
  'You go elbow-deep in wyvern shit and I\'m the weird one? -Tallis',
  'Blah, blah, blah! Obey me! Arrow in my face! -Sera',
  'I like having an article at the front. It makes it sound like I''m not even a person, just a mindless weapon, an implement of destruction...that really works for me. -The Iron Bull',
  'Whenever you need an ass kicked, The Iron Bull is with you. -The Iron Bull',
  'Don\'t get me wrong, I\'m sure you\'re careful and all, but I like my nipples uncauterized, thanks. -The Iron Bull',
  'The only way out of this game is to kill or be killed. -Leliana',
  'I\'m sure someone thought far too long about my name.',
  'Oooh, cloak and dagger phrases! How about... the queasy crow... flies at midnight? -Hawke',
  'Next time, could we hunt something small and cuddly? Maybe vegetarian? -Hawke',
  'If this is the afterlife the Chantry owes me an apology. This looks nothing like the Maker\'s bosom. -Hawke',
  'Seven people want your minstrel dead. They’d settle for smashing her lute, but they’re afraid she’d sing about it. -Cabot',
  'Thieves made off with our stores of cookie dough. Now it’s personal. -Cabot',
  'Rivaini, stop looking at my chest. My eyes are up here. -Varric',
  'Step one, we find Castillon... step two, I don\'t know. Something exciting happens. Step three, profit. Any questions? -Isabela',
  'Friend, if your brooding were any more impressive, women would swoon as you passed. They\'d have broody babies in your honor. -Varric',
  'Is brooding a sport in Tevinter? Do they hold competitions? Hand out trophies for the best scowls? -Varric',
  'So what\'s with that magical fisting thing you do? -Isabela',
  'Ser Pounce-a-lot... who knighted him? -Merrill',
  'Slattern! -Aveline',
  'I\'m the captain of the guard. I\'m loyal, strong, and I don\'t look too bad naked. -Aveline',
  'Strange, I always thought I\'d wind up arresting you some day. -Aveline',
  'Can I get  you something to eat or drink? I have * awkward pause* water. -Merrill',
]

%x(/usr/local/bin/terminal-notifier -message "#{da_quotes.sample}" -title "DA QotD")
